# Assignment 1

# Questions   1: 

# 1)   Numpy   Assignment: 

In [1]:
import numpy as np

# 1.) Eigenvalues and  Eigenvectors  of  an  array 

# Function:

# Syntax:

# Code:

In [2]:
#Create numpy 2D-array
a=np.array([[1,2],
            [2,3],
          ])
print("Print the original Square array:\n",a)

Print the original Square array:
 [[1 2]
 [2 3]]


In [3]:
#Find the eigenvalues and eigenvectors
w,v =np.linalg.eig(a)

#printing eigen values :

print("Printing the Eigen values of the given square array:\n",w)

print( )
# printing eigen vectors :

print("Printing eigenvectors of the given square array:\n",v)

Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]

Printing eigenvectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


# Application:

# 2) digitize()  

# Function:

# Syntax:

# Code:

In [4]:
x = np.array([0.2, 6.4, 3.0, 1.6])
bins = np.array([0.0, 1.0, 2.5, 4.0, 10.0])
inds = np.digitize(x, bins)
inds

array([1, 4, 3, 2], dtype=int64)

In [5]:
x = np.array([1.2, 10.0, 12.4, 15.5, 20.])
bins = np.array([0, 5, 10, 15, 20])

np.digitize(x,bins,right=False)


array([1, 3, 3, 4, 5], dtype=int64)

# 3) repeat() 

# Function:

# Syntax:

# Code:

In [6]:
np.repeat(3, 4)

array([3, 3, 3, 3])

In [7]:
x = np.array([[1,2],[3,4]])
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [8]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

# Application:

# 4) squeeze() 

# Function:

# Syntax:

# Code:

In [9]:
import numpy as np
a=np.array([[[0],[2],[4]]])
a.shape

(1, 3, 1)

In [10]:
np.squeeze(a).shape

(3,)

In [11]:
np.squeeze(a,axis=0).shape

(3, 1)

In [12]:
#np.squeeze(a,axis=1).shape
#Gives ValueError ->cannot select an axis to squeeze out which has size not equal to one

In [13]:
np.squeeze(a,axis=2).shape

(1, 3)

# 5) linspace() 

# Function:

# Syntax:

# Code:

In [14]:
np.linspace(2.0,3.0,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [15]:
np.linspace(2.0,3.0,num=5,endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [16]:
np.linspace(2.0,3.0,num=5,retstep=False)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [17]:
np.linspace(2.0,3.0,num=5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

# 6) clip() 

# Function:

# Syntax:

# Code:

In [22]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.clip(a,1,8)

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])

In [32]:
np.clip(a,3,6,out=a)


array([3, 3, 3, 3, 4, 5, 6, 6, 6, 6])

In [34]:
a=np.arange(12)
np.clip(a,3,9,out=a)

array([3, 3, 3, 3, 4, 5, 6, 7, 8, 9, 9, 9])

In [36]:
a=np.arange(12)
np.clip(a,[3,4,1,1,1,4,4,4,4,4,5,6],8)

array([3, 4, 2, 3, 4, 5, 6, 7, 8, 8, 8, 8])

# Application:

# 7) extract() 

# Function:

# Syntax:

# Code:

In [38]:
arr=np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
condition=np.mod(arr,3)==0
condition

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False]])

In [40]:
np.extract(condition,arr)

array([0, 3, 6, 9])

# 8) argpartition() 

# Function:

# Syntax:

# Code:

In [41]:
x = np.array([3, 4, 2, 1])
x[np.argpartition(x, 3)]

array([2, 1, 3, 4])

In [42]:
x[np.argpartition(x, (1, 3))]

array([1, 2, 3, 4])

In [45]:
x = np.array([[3, 4, 2], [1, 3, 1]])
index_array = np.argpartition(x, kth=1, axis=-1)
np.take_along_axis(x, index_array, axis=-1)  # same as np.partition(x, kth=1)

array([[2, 3, 4],
       [1, 1, 3]])

# 9) setdiff1d() 

# Function:

# Syntax:

# Code:

In [46]:
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])
np.setdiff1d(a, b)

array([1, 2])

In [47]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values in array1 that are not in array2:
[ 0 20 60 80]


# 10) itemsize 

# Function:

# Syntax:

# Code:

In [48]:
x = np.array([1,2,3], dtype=np.float64)
x.itemsize

8

In [49]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

# 11) hstack() 

# Function:

# Syntax:

# Code:

In [50]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [51]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [52]:
x = np.array([[3], [5], [7]])
y = np.array([[5], [7], [9]])
np.hstack((x,y))

array([[3, 5],
       [5, 7],
       [7, 9]])

# 12) vstack() 

# Function:

# Syntax:

# Code:

In [53]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [54]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [56]:
x = np.array([[3], [5], [7]])
y = np.array([[5], [7], [9]])
np.vstack((x,y))

array([[3],
       [5],
       [7],
       [5],
       [7],
       [9]])

# 13) hsplit()

# Function:

# Syntax:

# Code:

In [63]:
x = np.arange(16.0).reshape(4, 4)
x
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [64]:
np.hsplit(x, np.array([3, 6]))

[array([[ 0.,  1.,  2.],
        [ 4.,  5.,  6.],
        [ 8.,  9., 10.],
        [12., 13., 14.]]),
 array([[ 3.],
        [ 7.],
        [11.],
        [15.]]),
 array([], shape=(4, 0), dtype=float64)]

In [65]:
p = np.arange(8.0).reshape(2, 2, 2)
p

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [67]:
np.hsplit(p, 2)

[array([[[0., 1.]],
 
        [[4., 5.]]]),
 array([[[2., 3.]],
 
        [[6., 7.]]])]

# 14) vsplit() 

# Function:

# Syntax:

# Code:

In [68]:
a = np.arange(20.0).reshape(4,5)
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [69]:
np.vsplit(a, 2)

[array([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]]),
 array([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])]

In [70]:
np.vsplit(a, np.array([2, 5]))

[array([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]]),
 array([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]]),
 array([], shape=(0, 5), dtype=float64)]

In [71]:
x = np.arange(8.0).reshape(2, 2, 2)
x

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [72]:
np.vsplit(x, 2)

[array([[[0., 1.],
         [2., 3.]]]),
 array([[[4., 5.],
         [6., 7.]]])]

# 15) View vs Shallow  Copy

# Function:

# Syntax:

# Code:

In [73]:
#Copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [81]:
#view
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# 16) Deep Copy 

# Function:

# Syntax:

# Code:

In [80]:
import copy 
  
# initializing list 1  
li1 = [1, 2, [3,5], 4] 

  
# using deepcopy for deepcopy   
li3 = copy.deepcopy(li1)  
li3

[1, 2, [3, 5], 4]

In [78]:
import numpy as np
import copy

pairs = [(2, 3), (3, 4), (4, 5)]
array_of_arrays = np.array([np.arange(a*b).reshape(a,b) for (a, b) in pairs])

a = copy.deepcopy(array_of_arrays)
a

array([array([[0, 1, 2],
       [3, 4, 5]]),
       array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]),
       array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])], dtype=object)

# 17) copy() 

# Function:

# Syntax:

# Code:

In [84]:
x = np.array([1, 2, 3])
y = x
z = np.copy(x)
z

array([1, 2, 3])

# 18) meshgrid()

# Function:

# Syntax:

# Code:

In [85]:
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
xv

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])

In [86]:
yv

array([[0., 0., 0.],
       [1., 1., 1.]])

# 19) swapaxes() 

# Function:

# Syntax:

# Code:

In [88]:
x = np.array([[1,2,3]])
np.swapaxes(x,0,1)

array([[1],
       [2],
       [3]])

In [89]:
x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [90]:
np.swapaxes(x,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

# 20) column_stack()s 

# Function:

# Syntax:

# Code:

In [91]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])